on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: lmmodernizationreg.azurecr.io
        username: ${{ secrets.acr_lmmodernizationreg_username }}
        password: ${{ secrets.acr_lmmodernizationreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t lmmodernizationreg.azurecr.io/mattsk8sclusterdev:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push lmmodernizationreg.azurecr.io/mattsk8sclusterdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mattsk8sclusterdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep matts-k8s-cluster-dev86a4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace matts-k8s-cluster-dev86a4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: matts-k8s-cluster-dev86a4
        container-registry-url: lmmodernizationreg.azurecr.io
        container-registry-username: ${{ secrets.acr_lmmodernizationreg_username }}
        container-registry-password: ${{ secrets.acr_lmmodernizationreg_password }}
        secret-name: mattsk8sclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: matts-k8s-cluster-dev86a4
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          lmmodernizationreg.azurecr.io/mattsk8sclusterdev:${{ github.sha }}
        imagepullsecrets: |
          mattsk8sclusdockerauth
